### ISSUE TITLE
docker-compose -f docker-compose-dev.yaml up, and have error

### ISSUE THREAD

**Issue by DUC-ANH-LY** [mediacms-io/mediacms#1001]
![image](https://github.com/mediacms-io/mediacms/assets/92360920/a001920e
![Untitled](https://github.com/mediacms-io/mediacms/assets/92360920/4787669e-de5b-461a-937c-8368831c2827)
-c00d-4421-b635-d0a3ba47233a)
![Untitled](https://github.com/mediacms-io/mediacms/assets/92360920/9a5a0342-67c5-450c-bdd4-309b6648505c)

**Comment by mgogoulos** [comment]
Reopen with more info if you want, eg what env you are running etc. Is it Windows, or WSL?
