### ISSUE TITLE
Is MediaCMS dead?

### ISSUE THREAD

**Issue by miltuss** [mediacms-io/mediacms#1015]
Hello, MediaCMS has not had any updates for 6 months!
 Has the main developer abandoned this wonderful tool?

**Comment by mgogoulos** [comment]
Hi, it's true that I haven't been active at all lately, at least on this repository. Trying to find time to deal with the PRs and some of the issues, but also help onboard other people to the project

**Comment by miltuss** [comment]
This application is very good, it would be a really bad thing to abandon it. it's really the only one that looks like Youtube unlike peertube

**Comment by aquarde** [comment]
How do we support the developers?

**Comment by working-name** [comment]
@mgogoulos Did you change your mind about abandoning the project?

**Comment by mgogoulos** [comment]
Hi, I'm just too busy with other projects and don't have time and energy currently for even basic tasks here. Hopefully this will change soon. On the meanwhile I am looking for contracts and partnerships that will allow to spend more time here and be able to form and maintain a reliable team.

**Comment by homegrownhrbs** [comment]
I hope we can make it work this project is awesome!

**Comment by mgogoulos** [comment]
I had the chance to work on it these days and pushed some updates :) also there's a new partner that will work part time on fixing issues. We are back
