### ISSUE TITLE
ubuntu 22.04 > 24.04 update problem

### ISSUE THREAD

**Issue by heerbovec** [mediacms-io/mediacms#1053]
I have a single server mediaCMS installation (version 3) running on ubuntu 22.04. After a system update to ubuntu 24.04 I get an 502 error. Looking at the logs I notice that port 9000 is not available, even though it is defined in the config files. 

Any help would be much appreciated.

h.h.

**Comment by heerbovec** [comment]
Thanks for the prompt reply. I should have indicated some circumstances. I am working with vanilla 22.04 which I dist-upgraded to 24.04. No firewalls, no intervening daemon, mediaCMS ran just fine. According to the logs nginx just did not open port 9000 on 24.04.

[mediaCMS_logs.txt](https://github.com/user-attachments/files/17062533/mediaCMS_logs.txt)

Best,
h.h.

**Comment by heerbovec** [comment]
You seem to be right.  As far as I can tell uwsgi did not start.

[mediaCMS_logs_second_attempt.txt](https://github.com/user-attachments/files/17063904/mediaCMS_logs_second_attempt.txt)

Best, h.h.

**Comment by mgogoulos** [comment]
Can you run the uwsgi command and see if  it will load? I suspect that could be an issue with python not existing on the OS

Eg do the following and share the output:


```
source /home/mediacms.io/bin/activate
/home/mediacms.io/bin/uwsgi --ini /home/mediacms.io/mediacms/deploy/local_install/uwsgi.ini
```

**Comment by heerbovec** [comment]
mediacms cannot find "libpython3.10.so.1.0" even though it is installed (within a snap). Can this be the problem?

[mediacms_troubleshooting_3.txt](https://github.com/user-attachments/files/17074287/mediacms_troubleshooting_3.txt)

Thanks for your helpful guidance!
h.h.

**Comment by mgogoulos** [comment]
If it's not able to start, that should be the problem, however not sure if this is the only problem or if there are going to be other issues...

On a new Ubuntu 24.04 server in Hetzner, I tried the server install, and it didn't work out of the box. I didn't bother to do anything to fix, it would just didn't work. 

But then I tried with the Docker install, and it would complete without any issues. Do you consider running the Docker install?

**Comment by mgogoulos** [comment]
I'd suggest to purge it if you don't have lots of data (users, videos etc). In this case, you start fresh!

**Comment by heerbovec** [comment]
I  can now confirm that the current docker version of mediaCMS installs on ubuntu 24.04 straight away.
