### ISSUE TITLE
Integration of the French language into MediaCMS

### ISSUE THREAD

**Issue by miltuss** [mediacms-io/mediacms#1060]
Hello, many MediaCMS users are of French origin and it would be great to integrate the French language into this magnificent tool.

Could the French language be integrated into MediaCMS?

**Comment by mgogoulos** [comment]
Hi, I've been resuming a branch that adds translations, it should be available very soon. 

Regards
Markos

**Comment by miltuss** [comment]
> Hi, I've been resuming a branch that adds translations, it should be available very soon.
> 
> Regards Markos

Thank you very much, I really like this project and I am very happy that you are back again
