### ISSUE TITLE
Option for allowing only certain domains to register

### ISSUE THREAD

**Issue by yatesdr** [mediacms-io/mediacms#1085]
The config option RESTRICTED_DOMAINS_FOR_USER_REGISTRATION is good for banning domains, but I could find no option for a white-list of domains.  I would like a feature that only allows specific domains from a list to be registered and bans all other domains.

Proposal:  Add a key similar to:
ALLOWED_DOMAINS_FOR_USER_REGISTRATION = ["allowed.domain.com", "allowed.2.domain.com", ... ]

When set, it only allows the registration if the domain matches one in the list.

I'm considering using this as part of a company's internal training system for video delivery in an LMS, and it would be helpful to allow anybody from the domain to register, but nobody from other domains.

**Comment by yatesdr** [comment]
Tested locally, submitted as PR1086.

**Comment by mgogoulos** [comment]
thanks @yatesdr
