### ISSUE TITLE
[Improvement] Logo Replacement Option and Customization

### ISSUE THREAD

**Issue by mprajescu** [mediacms-io/mediacms#11]
Can you please provide some information on how to replace the logo and also how to modify the CSS files or if there are any other methods of customization?

**Comment by mprajescu** [comment]
Logo can be replaced if you only replace the files in "/home/mediacms.io/mediacms/cms/static/images" and it will always take the SVG file instead of the PNG. It should be something simple to setup, through an admin panel.

**Comment by mgogoulos** [comment]
Have opened https://github.com/mediacms-io/mediacms/issues/42 and can close this one!
