### ISSUE TITLE
Support for Debian 10 Buster

### ISSUE THREAD

**Issue by sthierolf** [mediacms-io/mediacms#112]
Just did a test installation on Debian 10 Buster. 

The install.sh script works fine by adding an additional elif block which tests for `lsb_release -d` == *"buster"*.

I think Debian 10 can be also included as supported distribution.

**Comment by mgogoulos** [comment]
Hi @sthierolf , good to read this!

**Comment by mgogoulos** [comment]
I'd like to try https://github.com/mediacms-io/mediacms/pull/128 and close this one
