### ISSUE TITLE
change password for users

### ISSUE THREAD

**Issue by mprajescu** [mediacms-io/mediacms#12]
When you first setup and run the server, it will automatically generate an admin password for you. 
How can you change the admin password through the website, without going into Django backend?

**Comment by mgogoulos** [comment]
There's a pull request that shows the change password link for all users - including admins. It was there but was hidden somehow! 
It's still available if you follow /accounts/password/change/ as a logged in user

**Comment by mgogoulos** [comment]
added on https://github.com/mediacms-io/mediacms/pull/26
