### ISSUE TITLE
[Feature] SSO with Authlib

### ISSUE THREAD

**Issue by mprajescu** [mediacms-io/mediacms#13]
Can you please implement OAuth 2 for user registration, user provisioning and SSO etc. 
I would really appreciate if I could be able to add my existing users in Keycloak and allow them to use this wonderful application. 

https://docs.authlib.org/en/latest/django/index.html 

Or even: 

https://django-oauth-toolkit.readthedocs.io/en/latest/

**Comment by mgogoulos** [comment]
Hi, please move this discussion to ideas section on https://github.com/mediacms-io/mediacms/discussions so we can continue the discussion there. 
django-allauth is integrated to handle user registration (providing lots of interesting options with little work involved) so we should see how this could potentially co-exist with these OAuth2 libs...

**Comment by mprajescu** [comment]
Moving this to discussions
