### ISSUE TITLE
Docker compose throwing error

### ISSUE THREAD

**Issue by shubhank-saxena** [mediacms-io/mediacms#130]
When I am running `docker-compose up`, it's showing the following error
```
ERROR: The Compose file './docker-compose.yaml' is invalid because:
services.migrations.depends_on contains an invalid type, it should be an array
```
@mgogoulos

**Comment by shubhank-saxena** [comment]
According to the docs of version 3 of docker-compose 
`Version 3 no longer supports the condition form of depends_on.`
http://docs.docker.oeynet.com/compose/compose-file/#depends_on

**Comment by swiftugandan** [comment]
You need to upgrade your docker-compose. From 1.27, the functionality that was in schema V2 was merged with V3, implying that healthchecks now work as before. 
* https://github.com/docker/compose/releases/tag/1.27.0
* https://github.com/compose-spec/compose-spec/blob/master/spec.md#depends_on

**Comment by shubhank-saxena** [comment]
Thank you so much @swiftugandan ! I apologise for not being informed about this.

**Comment by swiftugandan** [comment]
No worries
