### ISSUE TITLE
[Tool/Feature] Add pre-commit to ensure the code quality

### ISSUE THREAD

**Issue by shubhank-saxena** [mediacms-io/mediacms#131]
Since this repo contains python as well as Javascript code, I was thinking maybe we can have a sort of rule check in the form of pre-commit config, which can help us to maintain the code quality according to standard jslint and PEP conventions. 
@mgogoulos what do you think? 
If it's something that you feel we can add, please let me know. I can work on this!
Thank you!

**Comment by mgogoulos** [comment]
Sure, for Python we can definitely add pre-commit and set some standards

**Comment by mgogoulos** [comment]
Since the frontend code is handled on a separate repo (source code not on a public repository yet) let's focus on Python code here

**Comment by shubhank-saxena** [comment]
Thank you!
These are some of the tools that I have used and seen in various open-source python projects -
- isort - This helps to sort all the imports in various files on the basis of core imports, local imports and 3rd party imports (alphabetical order as well)
- flake8 - This is a tool that enforces PEP8 convention of python and helps to raise and check not utilised errors and some other common errors as well.
- black - It is an autoformatter maintained by the PSF (Python Software Foundation) for PEP8 and various other conventions.

These are some tools along with their respective configs can be used in pre-commit
@mgogoulos please let me know if you find these tools okay so that I will raise a PR implementing all of it.

**Comment by mgogoulos** [comment]
Sure, integrating all three of them would be a good contributio
