### ISSUE TITLE
[Improvement] Email verification not working

### ISSUE THREAD

**Issue by mprajescu** [mediacms-io/mediacms#14]
How does the application sends emails? Where do you enter your SMTP details to be able to send emails? 
Just registered with a test user and cannot receive confirmation email. I can verify the user automatically in django, but no email was received in the mailbox.

**Comment by mprajescu** [comment]
Email verification is actually working after you fill in the information in settings.py. However, this must be added to an admin panel of some sorts for easier access and not going into command line every time you need to make a change.

**Comment by mgogoulos** [comment]
[This configuration page](https://github.com/mediacms-io/mediacms/blob/main/docs/Configuration.md) has hints on customizations, including setting email. We'll soon replace it with more complete user and developer documentation
