### ISSUE TITLE
[Improvement] Disable User Registration

### ISSUE THREAD

**Issue by mprajescu** [mediacms-io/mediacms#15]
Please implement functionality to disable user registration so other users cannot register and only provisioned users can view content.

**Comment by mprajescu** [comment]
This can be achieved by modifying the settings.py file, however, it must be easily accessible and be able to change this setting through and Admin Panel.

**Comment by mgogoulos** [comment]
Glad you found your way out on this, we're covering the topic on the documentation (under development) - for now [the configuration page here](https://github.com/mediacms-io/mediacms/blob/main/docs/Configuration.md) shows hints including this one
