### ISSUE TITLE
Impossible to create a playlist that contains only audio files

### ISSUE THREAD

**Issue by malakhovks** [mediacms-io/mediacms#153]
I noticed a bug with careful use of the system.
Create empty playlist.
When adding **audio files** to an **empty playlist**, it is added, but if you go to the playlists section, then it is empty and the loading icon is spinning forever. All other playlists are also unavailable.
When adding audio files to a playlist that contains at least one video file, then everything works fine.

**Comment by mgogoulos** [comment]
thanks for reporting! It's fixed on https://github.com/mediacms-io/mediacms/pull/154, run a git pull to get the update and then restart mediacms
