### ISSUE TITLE
[Improvement] Disable User Automatic Login

### ISSUE THREAD

**Issue by mprajescu** [mediacms-io/mediacms#16]
After a user is successfully registered, without even having the email verified, it is automatically allowed to login into the system. 
Sometimes this is not a desired action. 

Can you please implement a way so administrators can disable the automatic login of newly registered users?

**Comment by mprajescu** [comment]
After checking through the settings.py file, I could see there are different options for not allowing users to automatically login, however, this would look much nicer in a Control Panel/Admin Settings page for the site and would like to push this for a request to implement this.

**Comment by mgogoulos** [comment]
Closing, will handle this on https://github.com/mediacms-io/mediacms/issues/42 and though better documentation
