### ISSUE TITLE
[Feature] Disable Media Download

### ISSUE THREAD

**Issue by mprajescu** [mediacms-io/mediacms#17]
Please implement functionality to disable media download button for public users or logged in users, globally, by the CMS Administrator. 
If it is not disabled by the administrator of the site, then the users that are posting their media content, they should have the option to decide if the Download button should show, or not, per media file.

**Comment by mgogoulos** [comment]
linked PR includes the 'Allow download' option per media file

**Comment by mgogoulos** [comment]
added on https://github.com/mediacms-io/mediacms/pull/26

**Comment by timfam** [comment]
A global option is still needed to hide the download link. Bad UX disabling per upload if the organization as rule don't allow downloads.

**Comment by mgogoulos** [comment]
There's still the option to hide all downloads, by setting `download: false` on templates/config/installation/features.html

This should be included on the documentation settings too

**Comment by timfam** [comment]
@mgogoulos thanks how do I help with docs?
