### ISSUE TITLE
SMTP Settings

### ISSUE THREAD

**Issue by HidYn** [mediacms-io/mediacms#193]
Hi,

Thanks for such a fantastic application. I'm trying to setup SMTP to an e-mail server that accepts anonymous connections (Windows based) which requires e-mails to be sent from a certain sender address.

DEFAULT_FROM_EMAIL = 'senderaddress@test.com'
EMAIL_HOST_PASSWORD = ''
EMAIL_HOST_USER = ''
EMAIL_USE_TLS = False
SERVER_EMAIL = DEFAULT_FROM_EMAIL
EMAIL_HOST = 'smtp.domain'
EMAIL_PORT = 25
ADMIN_EMAIL_LIST = ['info@mediacms.io']

I have set the above setting and keep getting connection refused.

ConnectionRefusedError: [Errno 111] Connection refused

Any help would be appreciated.

**Comment by Dan1ell** [comment]
This seems more like a discussion than an issue. Could you please move this to the discussion section?

That said, you haven't put any settings yet. Try using the settings from a gmail account you own e.g. [https://www.hesk.com/knowledgebase/index.php?article=72](https://www.hesk.com/knowledgebase/index.php?article=72)

And again please move this out of issues to discussions.

**Comment by HidYn** [comment]
Closing and moving to Discussion section. 

Thanks
