### ISSUE TITLE
Audio files not playing well

### ISSUE THREAD

**Issue by Anzumatsuri** [mediacms-io/mediacms#213]
**Describe the issue**
Uploading fails when trying to upload audio (.mp3 or .flac) files. Apparently encoding logs states something about "codec not currently supported in container" (see below screenshot).

**To Reproduce**
Steps to reproduce the issue:
1. Upload a .mp3 or .flac file
2. It will fail to upload

**Expected behavior**
It will upload the file successfully and is able to play the file. (See https://demo.mediacms.io/view?m=1rUTRo2lO)

**Screenshots**
![image](https://user-images.githubusercontent.com/52699436/120827001-93765b00-c58d-11eb-835e-ea28957ed863.png)
![image](https://user-images.githubusercontent.com/52699436/120827104-ae48cf80-c58d-11eb-9a51-af9cde83d565.png)

**Environment (please complete the following information):**
 - OS: Ubuntu 20.04.2 LTS
 - Installation method: Docker Install
 - Browser: Firefox

**Additional context**
Encoding logs from screenshot:
> nt_min=360 scenecut=40 intra_refresh=0 rc_lookahead=20 rc=crf mbtree=1 crf=23.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 vbv_maxrate=5250 vbv_bufsize=5250 crf_max=0.0 nal_hrd=none filler=0 ip_ratio=1.40 aq=1:1.00
> [mp4 @ 0x55f0cd075380] Could not find tag for codec h264 in stream #0, codec not currently supported in container
> Could not write header for output file #0 (incorrect codec parameters ?): Invalid argument
> Error initializing output stream 0:1 -- 
> [aac @ 0x55f0cd07bc40] Qavg: -nan
> Conversion failed!

**Comment by mgogoulos** [comment]
I'd like to test this locally, can you upload an mp3 and a flac file that file to load? After initial file upload the system performs a file identification, and in cases of music files it doesn't do anything. I assume the files in question contain other streams that confuse the file identification - this is why you see the Media Type as video. 
You may upload files on https://demo.mediacms.io/ and paste the links!

**Comment by Anzumatsuri** [comment]
Here are the links. Thanks!

https://demo.mediacms.io/view?m=d2i0vDrtG
https://demo.mediacms.io/view?m=01ZxrwN9C

**Comment by Anzumatsuri** [comment]
Good day, it has almost been a year since I have raised this issue. Any ETA on the fix? I assumed you are planning to have every issues resolved for the 2.0 release?

**Comment by mgogoulos** [comment]
Hi @Anzumatsuri , thanks for raising this issue, apparently I haven't found the time to debug, but I'm available to provide mentoring and will now add the good first issue label to it

**Comment by mgogoulos** [comment]
this is now fixed, audio files are better identified as such now. Should work on new installations, for existing ones
1. update the code
2. restart celery_long
3. you might have to manually trigger re-encode to files added that weren't identified correctly!
