### ISSUE TITLE
pids folder should exist only in container scope

### ISSUE THREAD

**Issue by swiftugandan** [mediacms-io/mediacms#224]
If the deployment mounts the entire source folder, the pids folder is visible to all containers. This means that when any of the containers are starting, they will clean up any existing pids see:
https://github.com/mediacms-io/mediacms/blob/de30fe68f12ea9e75880b501d217e1c51911213d/deploy/docker/entrypoint.sh#L14 ... Looks like this was a hack around a bigger issue...

We need to place the pid files within the scope of an individual container (eg in /var/run/) to prevent containers from interfering with PID files of other containers

**Comment by swiftugandan** [comment]
@mgogoulos this is resolved

**Comment by mgogoulos** [comment]
Thanks @swiftugandan !
