### ISSUE TITLE
[Issue] Reverse Proxy Server time out

### ISSUE THREAD

**Issue by mprajescu** [mediacms-io/mediacms#23]
I found out is that the application doesn’t work well with reverse proxy, eventually the app is no longer accessible after 30 minutes if you use reverse proxy. So far, what I could find out, is that the issue at hand might be with the reverse proxy, if you use access lists. Currently testing without having the restriction and looks ok for now. 

Will revert back with an update soon

**Comment by mgogoulos** [comment]
not sure what you mean here, please write a note what you used for a reverse proxy

**Comment by mprajescu** [comment]
I'm using Nginx Proxy Manager in Docker and i've setup an ACL list to deny public access to the site by having to enter a username and password. 
If i keep the ACL list, eventually, the application is no longer responding on 443 and cannot access the address, internally by IP or externally by going to the domain name, hitting the Nginx Proxy. If I restart just Nginx on the Ubuntu server, nothing happens. If I restart the Nginx Proxy Manager, nothing happens. It only works if I do systemctl restart mediacms and also restart Nginx Proxy Manager. It seems to only happen if I enable the ACL, so it might be related to that. 

Are there any logs I can pull and check for access?

**Comment by mprajescu** [comment]
This can be closed, I don't think it's related to only MediaCMS as I've experienced this with other applications. Might be something related to Nginx Proxy Manager.
