### ISSUE TITLE
Streamline Dev/Testing environment

### ISSUE THREAD

**Issue by mgogoulos** [mediacms-io/mediacms#233]
Provide 
a) an environment for testing
b) an environment for local development of all parts across the application (frontend, backend, workers)

Rough plan could be the following: 
- [ ] keep Dockerfile.yaml as it is now, make another file as Dockerfile-dev.yaml, add the extra dependencies there needed for the tests to run (eg selenium/pytest related) and also for local dev. An alternative would be to add a docker-compose-dev.yaml and add selenium-

- [ ] move out test/dev related libs to requirements-dev.txt

- [ ] copy the extra dependencies on the Github action config, so that tests work there using the Dockerfile.yaml - this seems to be ok

- [ ] in communication with @styiannis , make npm dependencies available on the Dockerfile-dev.yaml

- [ ] change entries (probably deploy/docker/start.sh ?) so that the test setup starts Django test server and also npm test server...

- [ ] write a good document on how to build a local image with Dockerfile-dev.yaml or docker-compose-dev.yaml, that will run all tests upon executing pytest . and will allow local development

**Comment by mgogoulos** [comment]
@styiannis @swiftugandan @shubhank-saxena and anyone else welcome to help with this

**Comment by chorylee** [comment]
agree with @mgogoulos , if  no Dev/Testing environment, its NOT real open source, and it can NOT get big support

**Comment by shubhank-saxena** [comment]
@mgogoulos I think we are done with points 1,2,3,4 with PR #218

**Comment by swiftugandan** [comment]
@mgogoulos this is done

**Comment by mgogoulos** [comment]
Yes, this is done, thanks @shubhank-saxena , @swiftugandan and @styiannis !
