### ISSUE TITLE
Add sponsorship links

### ISSUE THREAD

**Issue by slhck** [mediacms-io/mediacms#254]
![image](https://user-images.githubusercontent.com/582444/126770807-0d10b0dc-0999-44c8-ad58-8d2c0a2085c6.png)

You have not set up sponsorhip links yet. Perhaps people would like to sponsor your work! 😄

**Comment by mgogoulos** [comment]
The setup with Stripe/Github sponsors etc has taken some time, but is now public. 

Thanks for reminding this!!!
