### ISSUE TITLE
Video upload cause chunk done 400 error

### ISSUE THREAD

**Issue by yanhuixie** [mediacms-io/mediacms#279]
**Describe the issue**
Video upload cause chunk done 400 error.

**To Reproduce**
Steps to reproduce the issue:
1. download v1.5 zip 
2. unzip and docker-compose up -d
3. Error 400 occurred while uploading

**Expected behavior**
Upload video normally.

**Screenshots**
![微信图片_20210820172243](https://user-images.githubusercontent.com/1049615/130211843-598339b8-31c4-4f15-852f-3840eb44e9e1.png)

**Environment (please complete the following information):**
 - OS: Debian 10
 - Installation method: [Docker install]
 - Browser: Both Chrome 92 and Edge 92, Windows 10

**Additional context**
Different from the default configuration:
1, service web port: "9019:80"
2, FRONTEND_HOST = 'http://172.x.y.z:9019'

**Comment by mgogoulos** [comment]
This was caused due to a bug that is fixed on main branch, but I forgot to update the version too. Will publish a new version in the next few hours so you may try it out!

**Comment by mgogoulos** [comment]
Ok try out the new version, v1.6, it is just released! Check out instructions on https://github.com/mediacms-io/mediacms/releases if you want to update from your current version, alternatively remove the mediacms image and next time you run docker-compose (on v1.6) it will get the latest images

Don't forget to post other issues you find and anything else you consider as important. 

Best
Markos

**Comment by yanhuixie** [comment]
> Ok try out the new version, v1.6, it is just released! Check out instructions on https://github.com/mediacms-io/mediacms/releases if you want to update from your current version, alternatively remove the mediacms image and next time you run docker-compose (on v1.6) it will get the latest images
> 
> Don't forget to post other issues you find and anything else you consider as important.
> 
> Best
> Markos

Wow~ amazing, now 1.6 works.
Thanks for your quick awesome release and reply.
