### ISSUE TITLE
Import video metadata from JSON

### ISSUE THREAD

**Issue by kajatak** [mediacms-io/mediacms#292]
My videos have the relevant metadata in accompanied JSON files using properties such as `title`, `description` and `tags`, and I would like to have the ability to import all of this data to the database easily instead of having to manually do them one-by-one. This could probably be done from the admin panel as I think that it might just clutter the frontend metadata editor.

**Comment by mgogoulos** [comment]
Hi, I can create a small script so you can give it a try. I am assuming the file paths are also part of the json files, right?

**Comment by mgogoulos** [comment]
Moving this to discussions

@kajatak can you paste 2-3 JSON files (if each media is exported to a single JSON file)  so that I see what's there and direct you with a script?
