### ISSUE TITLE
My suggestions for improvemen

### ISSUE THREAD

**Issue by webdsf** [mediacms-io/mediacms#32]
1. How to force download not only mkv and mp4? I would like to add avi, vob.
2. Language packs, let users translate, you just give the opportunity. I can translate into Russian.
3. The problem is with Russian, there is no way to upload files that differ from English characters. And there is no way to change the name of the video other than English.  Also, I cannot change the description. _Server Error (500)_
4. Possible SubRip support, or transcoding at boot. (also the ability to get subtitles from the videocontainer)
5. Additional customization of encoding profiles, and adding new ones. Ability to bring out the settings for quality compression, sound directly from the admin panel. For easy creation of profiles for unknowing people.
6. For some reason, the vp9 profile does not work, I selected it, but the video is not encoded into it.
Someday it will be good to add support for ads, additional audio tracks, choice of storage space, storage in the clouds and ftp, prevent the inserted video from playing on certain domains.

I really liked the script, it works well for me with a weak VPS. And the quality is decent. There are simply not enough opportunities, I would even like to help as much as I can. I see potential here, and I believe in you! With the help of your script will be doing a lot of great-million projects!

**Comment by mgogoulos** [comment]
Hello, 
1) you mean uploading video files like avi? They are supported
2) planned for the near future
3) that's a bug, can confirm it, will work on a solution
5) possible, through the admin dashboard (/admin/files/encodeprofile/) , you can see what is available and enable/disable. To add new profiles however would require more work than adding them there. 
6) lots of good ideas here!
