### ISSUE TITLE
Wrong “Upload Failed” Info

### ISSUE THREAD

**Issue by cocova** [mediacms-io/mediacms#326]
I got "Upload failed" error for each uploading process (under the process bar), when I chose several video clips (about 5-6 video clips, and about 500MB per each one) to upload.
But later, I could see some of the video clips are uploaded successfully (I am not sure if all of them are uploaded successfully).
After checking logs under /home/mediacms.io/mediacms/logs, I found a lot of error/failed/false records like belows:

/home/mediacms.io/mediacms/logs/celery_long.log:129:[2021-11-18 13:32:58,416: ERROR/ForkPoolWorker-2] Task encode_media[25a73842-4c28-4cea-b46c-bf217f966a3c] raised unexpected: IntegrityError('insert or update on table "files_encoding" violates foreign key constraint "files_encoding_media_id_5ebc509a_fk_files_media_id"\nDETAIL:  Key (media_id)=(1) is not present in table "files_media".\n')
/home/mediacms.io/mediacms/logs/celery_long.log:165:    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
/home/mediacms.io/mediacms/logs/celery_long.log:178:[2021-11-18 13:32:58,439: INFO/ForkPoolWorker-2] Task encode_media[942b1e9a-076e-4624-b7a2-326989d40df3] succeeded in 0.020007179999083746s: False
/home/mediacms.io/mediacms/logs/celery_long.log:181:[2021-11-18 13:32:58,458: INFO/ForkPoolWorker-2] Task encode_media[776eec2d-e4f1-45fa-9d17-5163e4964780] succeeded in 0.013006910998228705s: False
/home/mediacms.io/mediacms/logs/celery_long.log:184:[2021-11-18 13:32:58,479: INFO/ForkPoolWorker-2] Task produce_sprite_from_video[57ea9e7e-1231-4ea0-8fb8-ffae5d4bd3d5] succeeded in 0.014189815999998245s: False
/home/mediacms.io/mediacms/logs/celery_long.log:187:[2021-11-18 13:32:58,495: INFO/ForkPoolWorker-2] Task encode_media[bb0a8c9e-5f54-476e-8db1-a8245b4189c7] succeeded in 0.009697108002001187s: False
/home/mediacms.io/mediacms/logs/celery_long.log:190:[2021-11-18 13:32:58,513: INFO/ForkPoolWorker-2] Task encode_media[f8caaa5d-5cf8-4b94-846b-f1b52f9bedaa] succeeded in 0.011913112000911497s: False
/home/mediacms.io/mediacms/logs/celery_long.log:193:[2021-11-18 13:32:58,531: INFO/ForkPoolWorker-2] Task encode_media[ee79be99-18c6-4882-9a08-f7110bcc7b9d] succeeded in 0.009683503998530796s: False
/home/mediacms.io/mediacms/logs/celery_long.log:196:[2021-11-18 13:32:58,561: INFO/ForkPoolWorker-2] Task produce_sprite_from_video[61cc363e-c3f2-469b-afa8-4b090446fb0d] succeeded in 0.02375301199936075s: False
/home/mediacms.io/mediacms/logs/celery_long.log:199:[2021-11-18 13:32:58,576: INFO/ForkPoolWorker-2] Task encode_media[28b1aa4d-6a97-4233-888c-3de3e17d53c9] succeeded in 0.012460526002541883s: False

and like these ones:
/home/mediacms.io/mediacms/logs/celery_long.log:347:    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
/home/mediacms.io/mediacms/logs/celery_long.log:359:[2021-11-18 13:34:19,782: ERROR/ForkPoolWorker-3] Task encode_media[c8833c03-2384-4cea-ab6c-e6efc9ec1159] raised unexpected: IntegrityError('insert or update on table "files_encoding" violates foreign key constraint "files_encoding_media_id_5ebc509a_fk_files_media_id"\nDETAIL:  Key (media_id)=(3) is not present in table "files_media".\n')
/home/mediacms.io/mediacms/logs/celery_long.log:395:    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
/home/mediacms.io/mediacms/logs/celery_long.log:407:[2021-11-18 13:34:33,478: ERROR/ForkPoolWorker-4] Task encode_media[5aa478b4-a7ab-48df-974b-ec7756c3eaf7] raised unexpected: IntegrityError('insert or update on table "files_encoding" violates foreign key constraint "files_encoding_media_id_5ebc509a_fk_files_media_id"\nDETAIL:  Key (media_id)=(3) is not present in table "files_media".\n')
/home/mediacms.io/mediacms/logs/celery_long.log:443:    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
/home/mediacms.io/mediacms/logs/celery_long.log:1141:[2021-11-18 14:04:29,178: ERROR/ForkPoolWorker-3] Task encode_media[ff9ae27a-0e59-4830-a210-9793ece79cc4] raised unexpected: IntegrityError('insert or update on table "files_encoding" violates foreign key constraint "files_encoding_media_id_5ebc509a_fk_files_media_id"\nDETAIL:  Key (media_id)=(8) is not present in table "files_media".\n')
/home/mediacms.io/mediacms/logs/celery_long.log:1177:    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)

What is the problem? And how could I fix it?

Thanks in advance .

**Comment by mgogoulos** [comment]
can you describe installation details and if video encodings eventually succeed?
