### ISSUE TITLE
Support for starting content at specific timestamp via GET variable.

### ISSUE THREAD

**Issue by sankasan** [mediacms-io/mediacms#343]
**Describe the feature you'd like**
Having support to open content (video/audio) at a specific timestamp would be very useful. Ideally this feature is supported across all existing features such as sharing and in comments. 

One could imagine this could be extended with a page for PDF's. 

**Describe alternatives you've considered**
There are no alternatives available.

**Additional context**
YouTube, amongst others, implements this via a GET variable called `t`. So linking to any video with the argument `?t=14` will start playing the video at 14th second. This implementation has a lot of benefits (fairly simple, known format, human readable) and is an industry standard. Following this convention would be preferred.

**Comment by MrPercheul** [comment]
There is now a PR for this : #430

**Comment by mgogoulos** [comment]
PR just got merged!
