### ISSUE TITLE
Support to tag users via `@YourName` in comments and send notification in case of these events.

### ISSUE THREAD

**Issue by sankasan** [mediacms-io/mediacms#344]
**Describe the feature you'd like**
Tagging users in comments would be very helpful. This would thrive discussion, enhance collaboration and improve the community around a MediaCMS instance. Preferably this includes auto complete. Example would be that writing `@m` would give a drop down list in which a user can pick (mouse, touch or keyboard driven) the user they like to tag, in this example `@mgogoulos`.

Ideally the fact that you've been notified can be shared via various means. Probably the easiest to integrate is email, as this service is already available, but having the actual comment in the email would already help. A direct link to the comment, especially in a longer thread of comments would be useful as well.

Additionally having an option add API hooks for other platforms would be very helpful as well. As an example a Direct Message via Slack would align more modern (fast/direct) collaboration.

**Describe alternatives you've considered**
This feature is currently not present. Naming users does not trigger a notification to that other person. Only the person who uploaded a video gets (optionally) an email when a comment is placed.

**Comment by sankasan** [comment]
https://github.com/mediacms-io/mediacms/pull/429

**Comment by mgogoulos** [comment]
work on this was merged!
