### ISSUE TITLE
Set admin passwort doesn't work

### ISSUE THREAD

**Issue by Tzzui** [mediacms-io/mediacms#349]
Installed through docker on Ubuntu 20: https://github.com/mediacms-io/mediacms/blob/main/docs/admins_docs.md#3-docker-installation

1. It does not automatically assign a password

This does not show up: "migrations_1     | Created admin user with password: gwg1clfkwf"

2. Login also does not work if you set the password in the docker-compose.yaml file

Only thing that worked was this: https://github.com/mediacms-io/mediacms/discussions/81#discussioncomment-451239

**Comment by mgogoulos** [comment]
that link contains some good advice on how to proceed with this problem indeed
