### ISSUE TITLE
Add SECURITY.md

### ISSUE THREAD

**Issue by JamieSlome** [mediacms-io/mediacms#392]
Hey there!

I belong to an open source security research community, and a member (@wjddnjs33) has found an issue, but doesn’t know the best way to disclose it.

If not a hassle, might you kindly add a `SECURITY.md` file with an email, or another contact method? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) this best practice to ensure security issues are responsibly disclosed, and it would serve as a simple instruction for security researchers in the future.

Thank you for your consideration, and I look forward to hearing from you!

(cc @huntr-helper)

**Comment by mgogoulos** [comment]
please use the contact methods on http://mediacms.io/

**Comment by JamieSlome** [comment]
@mgogoulos - thanks for this follow-up - will do! ❤️ 

If it is easier, you can also view the report directly here:
https://huntr.dev/bounties/ed0fd672-32cc-47e9-b876-ec46c8c3916f/

It is private and only accessible to maintainers with repository write permissions...
