### ISSUE TITLE
ERROR: The Compose file './docker-compose-dev.yaml' is invalid because: services.web.depends_on contains an invalid type, it should be an array

### ISSUE THREAD

**Issue by Megidd** [mediacms-io/mediacms#433]
When running this command:

```bash
cd /home/mediacms.io/mediacms
docker-compose -f docker-compose-dev.yaml up
```

This error is received:

> ERROR: The Compose file './docker-compose-dev.yaml' is invalid because:
services.web.depends_on contains an invalid type, it should be an array

Downgrading version by #419 fixed the error. But it's preferred not to downgrade.

### OS

Operating System: openSUSE Leap 15.3

### docker

Docker version 20.10.12-ce, build 459d0dfbbb51

### docker-compose

docker-compose version 1.25.1, build a82fef0

## Error screenshot

![image](https://user-images.githubusercontent.com/95064217/160079770-e8269d56-1a22-43ab-8195-938d18c03e98.png)

## Expected behavior

![image](https://user-images.githubusercontent.com/17475482/160080288-3100d2b8-9a4d-404b-a7ed-6341a4b31740.png)

**Comment by pandiloko** [comment]
I think I had something very similar. Make sure you have at least docker-compose 1.27.  

I did this in Ubuntu LTS:

 - `sudo apt remove docker-compose`
 - `sudo pip install docker-compose `

You can `pip install` with non-root but as I understand with root it is system-wide available, which was what i wanted.

**Comment by Megidd** [comment]
Thanks @pandiloko :smile: 

The error got resolved on my device by:

```bash
zypper rm docker-compose
pip install docker-compose
```

Docker-compose version is upgraded from:

```bash
docker-compose version 1.25.1, build a82fef0
```

To:

```bash
docker-compose version 1.29.2, build unknown
```

Now, the error is resolved:

```bash
systemctl start docker.service
docker-compose -f docker-compose-dev.yaml up
```

![image](https://user-images.githubusercontent.com/17475482/161814931-8bb8ec21-6faf-47b3-baac-12764743f0ac.png)
