### ISSUE TITLE
No admin user is created when installing in dev mode through Docker

### ISSUE THREAD

**Issue by masavini** [mediacms-io/mediacms#471]
**Describe the issue**
No `admin` user is created when installing in dev mode through Docker.

**To Reproduce**
Steps to reproduce the issue:
1. git clone https://github.com/mediacms-io/mediacms
2. cd mediacms
3. docker-compose -f docker-compose-dev.yaml build
4. docker-compose -f docker-compose-dev.yaml up

**Docker relevant log part**
```
[...]
mediacms-web-1       |   Applying socialaccount.0003_extra_data_default_dict... OK
mediacms-web-1       | Running loaddata and creating admin user
mediacms-web-1       | Installed 22 object(s) from 1 fixture(s)
mediacms-web-1       | Installed 6 object(s) from 1 fixture(s)
mediacms-web-1       | CommandError: Username cannot be blank.       <<<<<<<<<<<<
mediacms-web-1       | Created admin user with password: vk589fprxd
mediacms-web-1       | RUNNING COLLECTSTATIC
[...]
```

**Environment (please complete the following information):**
 - OS: Ubuntu Linux
 - Installation method: Docker install
-----------------------------------------
A simple workaround is running `python manage.py createsuperuser`, but I guess something should be fixed in `deploy/docker/prestart.sh`: it looks like `$ADMIN_USER` variable is unset...

**Comment by Mozitux** [comment]
Hi, in which Ubuntu version are you trying to install MediaCMS? Have you the same issue when you try in Single Server?

**Comment by masavini** [comment]
ubuntu 16.04 with docker engine 20.10.9.
i didn't try single server installation.

the issue, however, was solved adding admin usr and pwd to the `environment` section of the docker-compose file (see pull request for details).
