### ISSUE TITLE
When a video is deleted, its thumbnails are not.

### ISSUE THREAD

**Issue by masavini** [mediacms-io/mediacms#491]
**Describe the issue**
When a video is deleted, its thumbnails are not.

**To Reproduce**
Steps to reproduce the issue:
1. Upload a video
2. Delete it
3. Video thumbnails are still there

**Expected behavior**
I'd expect thumbnails to be deleted.

**Environment (please complete the following information):**
 - OS: Arch Linux
 - Installation method: Docker install

**Comment by mgogoulos** [comment]
Can confirm this is happening, without being able to know why :(  When a video is uploaded, there's a number of thumbnails that is generated, and it seems that all of them are explicitly named with their paths and are removed, except some that aren't . It could be that they are created as temp files or that the function that creates thumbnails is called more than once, and every time it is called it is losing the association with the file (and thus the file stays on the filesystem as stale). Needs more exploration

**Comment by masavini** [comment]
i solved this in a rude way:
```python
# remove extra zombie thumbnails
import glob
if instance.thumbnail:
    thumbnails_path = os.path.dirname(instance.thumbnail.path)
    thumbnails = glob.glob(f'{thumbnails_path}/{str(instance.uid).replace("-", "")}.*')
    for thumbnail in thumbnails:
        os.remove(thumbnail)
```

i can submit a pull request if you want to...

**Comment by mgogoulos** [comment]
sure, please do that! I suggest you wrap the os.remove under a tr/except OSError case - the way other files are deleted are using files.helpers.rm_file that is just doing this

cheers

**Comment by masavini** [comment]
please see #657

**Comment by masavini** [comment]
should be fine, now
