### ISSUE TITLE
[Bug] issues with player on iPad/Safari

### ISSUE THREAD

**Issue by mgogoulos** [mediacms-io/mediacms#5]
As reported by jasonv:

```
I get only audio on the demo, using my iPad. No video.
9.7in iPad Pro, iPadOS 14.2, Safari.
```

**Comment by Dan1ell** [comment]
I can confirm this. Only audio on iPad.

**Comment by DieProgrammIDE** [comment]
Is there some workaround i could use?

**Comment by DieProgrammIDE** [comment]
@mgogoulos @Dan1ell i have created a workaround. If you need this you can install my Version to your Server ...

**Comment by mgogoulos** [comment]
PR has been applied, this should be fine - if not let's open another issue please!
