### ISSUE TITLE
Media CMS responses "Forbidden" as anonymus 

### ISSUE THREAD

**Issue by keineAngabe03** [mediacms-io/mediacms#502]
**Issue**
I'm trying to watch videos anonymus (not logged in). The following Message appears in the console of my Browser: /api/v1/media 403 (Forbidden)

![image](https://user-images.githubusercontent.com/111520648/185469709-c42ee912-86cf-4861-abc8-5ea707afa907.png)

When I am trying to do it logged on or directly over the IP of the Media CMS Server it works.
Do I need to add anything in local_settings.py to allow access via the reverse proxy?

**Installation**
I am using Media CMS behind a Apache2 Reverse Proxy Server.
![image](https://user-images.githubusercontent.com/111520648/185471597-426f2c74-7cb5-498f-84eb-bd7f1f607020.png)

The Apache server is configured as follows:
`<IfModule mod_ssl.c>
<VirtualHost *:443>
ServerName mydomain.io
ProxyPreserveHost On
DocumentRoot /var/www/html
ProxyPass /.well-known !
ProxyPass / http://ipOfMyMediaCmsServer/
ProxyPassReverse / http://ipOfMyMediaCmsServer/
RequestHeader set X-Forwarded-Proto "https"
RequestHeader set X-Forwarded-Port "443"
SSLCertificateFile /etc/letsencrypt/live/video.arnbrucker-theatergruppe.de/fullchain.pem
SSLCertificateKeyFile /etc/letsencrypt/live/video.arnbrucker-theatergruppe.de/privkey.pem
Include /etc/letsencrypt/options-ssl-apache.conf
</VirtualHost>
</IfModule>`

The MediaCMS Server is a new blank installation on a Proxmox Ubuntu 20.04 Container. I insatalled it via the Single Server Script. I didn't change the localhost entry. The local_settings.py contains the following:
`HOST='http://localhost'
PORTAL_NAME='MediaCMS
SSL_FRONTEND_HOST = FRONTEND_HOST.replace('http', 'https')
SECRET_KEY='[Secret Key]'
LOCAL_INSTALL = True`

**Environment**
 - OS:  Ubuntu 20.04 Container (Proxmox)
 - Installation method: single server install
 - Browser: various versions of Opera and Edge

**Comment by Micrufun** [comment]
@keineAngabe03 I'm curious what was the issue cause? How did you resolve it?

**Comment by keineAngabe03** [comment]
I'm not sure what ultimately solved the error, but I think it was adding the following line to local_settings.py: `ALLOW_ANONYMOUS_ACTIONS = []`
After restarting the mediacms service it worked.
