### ISSUE TITLE
Server Error (500) on Login/Register pages

### ISSUE THREAD

**Issue by Anzumatsuri** [mediacms-io/mediacms#51]
Huge thanks for providing this wonderful CMS. I have deployed the docker version and everything was working fine till now. 
I am currently getting a Server Error (500) on both the login and register pages, as well as the django login page. I tried restarting and redeploying the containers but still no luck.

I did updated the default admin account's profile (full name, email) and password. I have around 40 videos uploaded as well, if that meant anything. I have also ticker around with the django settings for a bit too.

Found this snippet in debug.log:

> Internal Server Error: /admin/login/
> Traceback (most recent call last):
>   File "/home/mediacms.io/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
>     response = get_response(request)
>   File "/home/mediacms.io/lib/python3.8/site-packages/django/core/handlers/base.py", line 179, in _get_response
>     response = wrapped_callback(request, *callback_args, **callback_kwargs)
>   File "/home/mediacms.io/lib/python3.8/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
>     response = view_func(request, *args, **kwargs)
>   File "/home/mediacms.io/lib/python3.8/site-packages/django/contrib/admin/sites.py", line 410, in login
>     return LoginView.as_view(**defaults)(request)
>   File "/home/mediacms.io/lib/python3.8/site-packages/django/views/generic/base.py", line 70, in view
>     return self.dispatch(request, *args, **kwargs)
>   File "/home/mediacms.io/lib/python3.8/site-packages/django/utils/decorators.py", line 43, in _wrapper
>     return bound_method(*args, **kwargs)
>   File "/home/mediacms.io/lib/python3.8/site-packages/django/views/decorators/debug.py", line 89, in sensitive_post_parameters_wrapper
>     return view(request, *args, **kwargs)
>   File "/home/mediacms.io/lib/python3.8/site-packages/django/utils/decorators.py", line 43, in _wrapper
>     return bound_method(*args, **kwargs)
>   File "/home/mediacms.io/lib/python3.8/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
>     response = view_func(request, *args, **kwargs)
>   File "/home/mediacms.io/lib/python3.8/site-packages/django/utils/decorators.py", line 43, in _wrapper
>     return bound_method(*args, **kwargs)
>   File "/home/mediacms.io/lib/python3.8/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
>     response = view_func(request, *args, **kwargs)
>   File "/home/mediacms.io/lib/python3.8/site-packages/django/contrib/auth/views.py", line 63, in dispatch
>     return super().dispatch(request, *args, **kwargs)
>   File "/home/mediacms.io/lib/python3.8/site-packages/django/views/generic/base.py", line 98, in dispatch
>     return handler(request, *args, **kwargs)
>   File "/home/mediacms.io/lib/python3.8/site-packages/django/views/generic/edit.py", line 133, in get
>     return self.render_to_response(self.get_context_data())
>   File "/home/mediacms.io/lib/python3.8/site-packages/django/contrib/auth/views.py", line 97, in get_context_data
>     current_site = get_current_site(self.request)
>   File "/home/mediacms.io/lib/python3.8/site-packages/django/contrib/sites/shortcuts.py", line 13, in get_current_site
>     return Site.objects.get_current(request)
>   File "/home/mediacms.io/lib/python3.8/site-packages/django/contrib/sites/models.py", line 58, in get_current
>     return self._get_site_by_id(site_id)
>   File "/home/mediacms.io/lib/python3.8/site-packages/django/contrib/sites/models.py", line 30, in _get_site_by_id
>     site = self.get(pk=site_id)
>   File "/home/mediacms.io/lib/python3.8/site-packages/django/db/models/manager.py", line 85, in manager_method
>     return getattr(self.get_queryset(), name)(*args, **kwargs)
>   File "/home/mediacms.io/lib/python3.8/site-packages/django/db/models/query.py", line 429, in get
>     raise self.model.DoesNotExist(
> django.contrib.sites.models.Site.DoesNotExist: Site matching query does not exist.

Thank you.

**Comment by Anzumatsuri** [comment]
Ahhh looking at the error snippet, I did remember changing the sites to match my domain, which resulted in a different SITE_ID.
I have added the variable to local_settings.py with the updated SITE_ID and it resolved the issue.

A documentation regarding this would be nice in the future. 👍

**Comment by mgogoulos** [comment]
hi, can you open an issue for the long file name? I can handle this instantly

thanks! Good to read you've figured the issue with the SITE_ID

**Comment by Anzumatsuri** [comment]
I have opened an issue regarding the long file name. Thanks!
