### ISSUE TITLE
Problems setting up over docker-compose with seperate proxy.

### ISSUE THREAD

**Issue by paultroeger** [mediacms-io/mediacms#512]
Hello!

I am having multiple problems setting up my mediacms instance over the docker-compose.yaml file.
Firstly docker warns me that the `condition: service_healthy` is no longer supported. 
So I changed that to
```
depends_on:
      - redis
      - db
```

After that mediacms can be started over docker-compose but the website has problems functioning. 
The firefox console outputs problems when trying to reach subpaths such as `/api/v1/categories` with the Error `500 Internal Server Error`.

This is my nginx setup file:
```
server {
	
	listen 443 ssl http2;

	server_name mediacms.mysite.tld;
	
	location / {
		proxy_pass http://127.0.0.1:8408/;
		proxy_set_header X-Forwarded-Host $host;
                proxy_set_header X-Forwarded-Server $host;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto https;
		proxy_set_header X-Forwarded-Port 443;
	}

        client_max_body_size 5G;
        charset utf-8;
}

server {
	
	listen 80;

	server_name mediacms.mysite.tld;

	return 301 https://$host$request_uri;
}
```

I've also added the lines:
```
USE_X_FORWARDED_HOST = True
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
```
inside the settings.py file per recommendation of issue #500.

Sadly the problem persists. 
Does anyone have a solution or can point me in a new direction? 

Best Regards,
Paul

**Comment by Micrufun** [comment]
About this problem:

> Firstly docker warns me that the condition: `service_healthy` is no longer supported.

Maybe this resolved issue helps: https://github.com/mediacms-io/mediacms/issues/433

**Comment by paultroeger** [comment]
Thank you for pointing me to that!
Sadly I still have a problem with the subpaths not being reachable.

**Comment by paultroeger** [comment]
I got it to work!
My first error was editing the docker-compose file to move the postgres_data into the mediacms folder. 
Since there are more settings that want to access this location it didn't work. 

After that I got an "Blocked loading mixed active content" Error when trying to open a video on the site. 

I fixed that by changing the nginx settings to:
```
location / {
		proxy_pass http://127.0.0.1:8408/;
		proxy_http_version 1.1;
		proxy_set_header X-Forwarded-Host $host;
                proxy_set_header X-Forwarded-Server $host;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
		proxy_set_header X-Forwarded-Proto $scheme;
                proxy_set_header Host $http_host;
                proxy_set_header X-Real-IP $remote_addr;
}
```
Now it seems to work.
Hope it helps someone else.

Best Regards,
Paul

**Comment by mgogoulos** [comment]
thanks for sharing these notes!
