### ISSUE TITLE
Add  customize Ads system

### ISSUE THREAD

**Issue by charl3s-cli** [mediacms-io/mediacms#534]
1. Customized Page Ads
2. Customized  Ads when the video plays （for example，start playing, every 5 minutes or every 15 minutes）

**Comment by mgogoulos** [comment]
Hi, I'm closing this as it is not something I plan to work on and I don't want the tracker to be full of requests that won't be handled. Sure if one works on it and creates the PR we can discuss it, but it's out of the scope of the software or my interests!
