### ISSUE TITLE
Upload Multiple Video Contents

### ISSUE THREAD

**Issue by devilmind81** [mediacms-io/mediacms#536]
Hi,
I have 10 Gb of videos to upload (more then thousands) and those are organized in folders and categories.
There is a possibility to copy those in a specific MediaCMS folder so the tool automatically load (upload) and shows on the website?
Should be frustrating for me to manually upload each video.
Thanks in advance for you attention.

**Comment by mgogoulos** [comment]
Hi, what you can do is move all videos to a single folder and then upload to MediaCMS through drag and drop - you can select multiple files and the limit is 100 out of the box but it is configurable too. Of course you are losing the categories and hierarchy doing this...but there is not a solution to specify a single folder and have folders/categories being created and items getting assigned there. That would be a good feature to develop and it has been asked in the past.

**Comment by devilmind81** [comment]
Hi, thanks for reply. Yes could be a nice feature that to specify for example the path a root folder of the videos and when the tool booting up could analize it in order to create categories from the folder and load/parsing all video into it.
I will try to open a request to ask it.
Thanks a lot
