### ISSUE TITLE
Subtitles don't appear to actually display when watching a video

### ISSUE THREAD

**Issue by KyleMaas** [mediacms-io/mediacms#555]
**Describe the issue**
If I pull up a video which has had subtitles added to it, the subtitle button in the player pops up and lets me select the language of the uploaded subtitles, but they do not show up in the player.  If I test the exact same subtitle file in VLC, it works.

**To Reproduce**
Steps to reproduce the issue:
1. Upload video
2. Upload subtitles
3. View video
4. Select subtitle language on the CC button
5. No subtitles are displayed

**Expected behavior**
I would expect to see subtitles, like I can in other video players.

**Screenshots**
Can't share the video, unfortunately.

**Environment (please complete the following information):**
 - OS: Server on Ubuntu Linux 20.04.5, client on Gentoo Linux
 - Installation method: single server install
 - Browser: Chromium or Firefox - have tried it in both

**Comment by KyleMaas** [comment]
Figured it out.  Subtitle files worked fine in VLC, but failed validation here:

https://w3c.github.io/webvtt.js/parser.html

Once fixed so they were valid, the player side works.

**Comment by cphpi** [comment]
iphone cannot display
