### ISSUE TITLE
Documentation on setup using MySQL instead of PostgreSQL

### ISSUE THREAD

**Issue by KyleMaas** [mediacms-io/mediacms#571]
**Describe the feature you'd like**
Django supports running atop MySQL.  It would be nice if the setup instructions gave alternate instructions for using MySQL from the start instead of assuming PostgreSQL.

**Comment by mgogoulos** [comment]
I will close this as there are some features that work only with PG - as the full text search / vector search and this prohibits the usage of MySQL or another DB...

**Comment by KyleMaas** [comment]
Is there a full list of the components that rely on Postgres-specific features?  Reason being that it would be quite nice if I could run MediaCMS on MySQL Galera clusters.

**Comment by mgogoulos** [comment]
> Is there a full list of the components that rely on Postgres-specific features? Reason being that it would be quite nice if I could run MediaCMS on MySQL Galera clusters.

Hi, that would be 

```
files/feeds.py:from django.contrib.postgres.search import SearchQuery
files/models.py:from django.contrib.postgres.indexes import GinIndex
files/models.py:from django.contrib.postgres.search import SearchVectorField
files/views.py:from django.contrib.postgres.search import SearchQuery
```

basically, search relies on GinIndex (https://docs.djangoproject.com/en/4.1/ref/contrib/postgres/indexes/) and PostgreSQL related functionality  (https://docs.djangoproject.com/en/4.1/ref/contrib/postgres/) there's a chance that this is now supported for MySQL as well but this has definitely not been the case 2-3 years ago

**Comment by KyleMaas** [comment]
Cool.  That gives me something to go on.  Thanks!
