### ISSUE TITLE
docker-compose - it should be an array?

### ISSUE THREAD

**Issue by mrhhats** [mediacms-io/mediacms#573]
Hi everyone! having a issue after grabbing latest version and trying to run docker-compose up.

Getting this error.

root@linuxapps:~/mediacms# docker-compose up
ERROR: The Compose file './docker-compose.yaml' is invalid because:
services.migrations.depends_on contains an invalid type, it should be an array
root@linuxapps:~/mediacms# 

I did apt-get upgrade/update to ensure I have all things updated. Ubuntu 20.04.1

thanks in advance.

**Comment by mgogoulos** [comment]
glad that was resolved
