### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by insurrectus** [mediacms-io/mediacms#574]
Run the install script for MediaCMS.  Everything is fine until it tries to validate Let's Encrypt.  I've tried both using localhost and putting my domain name.  I'm using cloudflare for DNS and nginx proxy manager.  I've tried shutting off the proxy on cloudflare, I've tried it with cloudflare proxying.  I still get Internal server error.  

I've tried multiple times and getting to the point of giving up.  I've searched for an answer, but haven't found one yet.  

**Environment (please complete the following information):**
 - OS: Debian 10
 - Installation method:  single server install

**Comment by mgogoulos** [comment]
Closing, if you think it's relevant reopen and provide more info
