### ISSUE TITLE
Trouble Clearing State

### ISSUE THREAD

**Issue by MikeyYeahYeah** [mediacms-io/mediacms#62]
I used the docker-compose.yml script to stand up my environment. I have tried running `docker-compose rm` and manually deleting all images and exited containers I could find related to MediaCMS.  I even blew out the cloned MediaCMS directory. No matter what I do, there is still some lingering state whenever I redeploy.

What am I missing?  Thank you!

**Comment by mgogoulos** [comment]
Adding @swiftugandan that has created the Docker Compose support, can you provide some hints? 
Thanks

**Comment by MikeyYeahYeah** [comment]
Slightly off-topic but needs to be said. This project is so awesome!  Thanks to all involved!

**Comment by swiftugandan** [comment]
if you used the docker-compose.yaml (default) the database state is stored a level outside the source. Ie.  ../postgres_data

**Comment by MikeyYeahYeah** [comment]
Ahh I see that directory now!  I will try removing that directory and reworking line 65.  

IMO storing state outside the directory is a little unintuitive.  It definitely caught me a little off guard. Is there any special reason for this?

**Comment by swiftugandan** [comment]
I want to separate the source from the data (for local mount method)... Not fully done that yet, as media and logs still get dumped in the source folder.

**Comment by MikeyYeahYeah** [comment]
In my experience, I enjoy having the 3rd party storage set to the source directory by default. I can easily mount a different volume if I need to.  It just makes it easier to backup and clean up if I need to.

**Comment by swiftugandan** [comment]
There is another reason I forgot to mention, the entrypoint.sh script changes the ownership of the source folder to www-data

https://github.com/mediacms-io/mediacms/blob/47f22790985b0c55b861d7ead737fed0a75a5dbb/deploy/docker/entrypoint.sh#L15

That means that you are likely to get a condition where the app always resets the ownership of the postgres folder after it has been created. The DB will have ownership issues after this ...
