### ISSUE TITLE
Docker: failed to create shim task...entrypoint.sh: no such file or directory: unknown

### ISSUE THREAD

**Issue by Snake883** [mediacms-io/mediacms#675]
I am trying to install and run MediaCMS the first time as a Docker container.

I am using Docker Compose and the [yaml](https://raw.githubusercontent.com/mediacms-io/mediacms/main/docker-compose.yaml) file.  I've made no other edits or custom configuration changes (copy, paste, compose).

When I bring Compose Up, I receive this output with an error message:

```
[+] Running 4/6
 ⠿ Container test-db-1             Waiting                                                                                                                      37.3s
 ⠿ Container test-redis-1          Healthy                                                                                                                      37.3s
 ⠿ Container test-celery_beat-1    Starting                                                                                                                     36.3s
 ⠿ Container test-migrations-1     Recreated                                                                                                                     2.0s
 ⠿ Container test-web-1            Recreated                                                                                                                     1.9s
 ⠿ Container test-celery_worker-1  Recreated                                                                                                                     1.9s
Error response from daemon: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "./deploy/docker/entrypoint.sh": stat ./deploy/docker/entrypoint.sh: no such file or directory: unknown
```

**Comment by behzad1993** [comment]
Same Problem here, tried different solutions. Portainer (standalone) and also TrueNas Scale with docker compose will give me this message. Just the clean docker-compose script can run it..

**Comment by klausmcm** [comment]
Have you made any changes to the `volumes` in the docker compose file?

**Comment by klausmcm** [comment]
I'm not sure if this is the cause of your issue but the docker image and `docker-compose` file are not sufficient to create a working container of mediacms. What I also need were the folders and files in this repo - especially the `cms` and `deploy` folder with contents need to be available when creating the container. If you change `volumes` to a custom folder, copy the contents from this repo into that folder and try creating the container again.

**Comment by codevski** [comment]
> I'm not sure if this is the cause of your issue but the docker image and `docker-compose` file are not sufficient to create a working container of mediacms. What I also need were the folders and files in this repo - especially the `cms` and `deploy` folder with contents need to be available when creating the container. If you change `volumes` to a custom folder, copy the contents from this repo into that folder and try creating the container again.

This should seriously be in the readme spent so much time trying to figure this out. Both folders CMS and Deploy need to be mapped. This should be part of the image setup copying files to the set volume you defined...

**Comment by kanwarplaha** [comment]
I still get the same error:
```
redis-1  | 1:M 26 Sep 2025 12:44:06.216 * Server initialized
db-1     | 2025-09-26 13:44:06.251 BST [1] LOG:  starting PostgreSQL 17.2 on x86_64-pc-linux-musl, compiled by gcc (Alpine 14.2.0) 14.2.0, 64-bit

db-1     | 2025-09-26 13:44:06.251 BST [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
redis-1  | 1:M 26 Sep 2025 12:44:06.216 * Ready to accept connections tcp
db-1     | 2025-09-26 13:44:06.251 BST [1] LOG:  listening on IPv6 address "::", port 5432
db-1     | 2025-09-26 13:44:06.253 BST [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
db-1     | 2025-09-26 13:44:06.257 BST [29] LOG:  database system was shut down at 2025-09-26 13:42:05 BST
db-1     | 2025-09-26 13:44:06.264 BST [1] LOG:  database system is ready to accept connections
Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: exec: "./deploy/docker/entrypoint.sh": stat ./deploy/docker/entrypoint.sh: no such file or directory: unknown
```
I am in the root of the cloned repository and `deploy/docker/entrypoint.sh` exists.

How can I resolve this?
