### ISSUE TITLE
[Feature] provide frontend React code

### ISSUE THREAD

**Issue by lotux** [mediacms-io/mediacms#7]
I was wondering if UI part of the application is also open-source, it seems UI code is missing

**Comment by mgogoulos** [comment]
Hello, yes, it will be uploaded soon in https://github.com/mediacms-io as a different project

**Comment by styiannis** [comment]
> I was wondering if UI part of the application is also open-source, it seems UI code is missing

Hi swiftugandan,

At the moment only the final built files of front end code (js/css) are available as part of MediaCMS code repository. An code repository is being prepared that will include the entire front end development environment, but it will take some time as we work on some new features that soon will be added to the platform.

**Comment by phreaknerd** [comment]
Any progress on this? Asking for a friend... ;-)

**Comment by malakhovks** [comment]
Yeah, it will be very useful for all of us

**Comment by distantbit** [comment]
Any update on this?

**Comment by phreaknerd** [comment]
@mgogoulos @styiannis If you guys need help "cleaning up" the frontend-code before it lands in this repo: I'm sure we can assemble a team (maybe outside github if you have concerns about issues) to support you. 
Most of us know very well how code may look before it's released into the wild... don't be shy - we won't blame you! :-)

**Comment by distantbit** [comment]
> @mgogoulos @styiannis If you guys need help "cleaning up" the frontend-code before it lands in this repo: I'm sure we can assemble a team (maybe outside github if you have concerns about issues) to support you.
> Most of us know very well how code may look before it's released into the wild... don't be shy - we won't blame you! :-)

I think that is not the point. It is not a matter of trust than a matter of contribution. As mentioned in #10 it would be helpful for any kind of translation because the most of UI strings are in the obfuscated front-end code.

**Comment by phreaknerd** [comment]
@distantbit As you can see in #20 there are many (including you and me) willing to support translations . But this requires the source code of the frontend to be released. 
Sometimes there are somewhat ugly hacks in the code (or security issues) blocking a release because the developer has no time to fix them neither want to show publicly. In that case we would setup a safe/private-room to fix that with a small-team as fast as possible so that we can release the frontend for further support by the community.

**Comment by mgogoulos** [comment]
Your points @phreaknerd are very valid, thanks for contributing to the discussion.

OK finally some good news here, there's a branch https://github.com/mediacms-io/mediacms/tree/frontent-dev-env that adds frontend/ folder along with some base instructions! Please help us with testing all functionality, make suggestions about the workflow for dev/production and we should be ready to merge this very soon!

**Comment by phreaknerd** [comment]
Well done! Thanks @mgogoulos!
I have tested a build on Ubuntu 16 with nvm/yarn. Had to install some dependencies manually and go to latest stable nodejs with nvm. The install and build with yarn worked flawlessly.

I'll try to add some documentation to the README regarding the dependencies.

**Comment by mgogoulos** [comment]
This is good news!

**Comment by swiftugandan** [comment]
> Your points @phreaknerd are very valid, thanks for contributing to the discussion.
> 
> OK finally some good news here, there's a branch https://github.com/mediacms-io/mediacms/tree/frontent-dev-env that adds frontend/ folder along with some base instructions! Please help us with testing all functionality, make suggestions about the workflow for dev/production and we should be ready to merge this very soon!

The branch is gone! @mgogoulos

**Comment by mgogoulos** [comment]
My bad, restored the branch just now!

**Comment by swiftugandan** [comment]
@mgogoulos how do you use the backend running on the local machine as an API server for the react app? ... 

eg. Attempting to upload tries to upload to http://localhost:8097/... instead of http://localhost/...

I also imagine the browser would block the requests to the backend because of CORS restrictions

**Comment by mgogoulos** [comment]
There are issues with the URLs, the plan is to merge this soon and make improvements afterwards

**Comment by mgogoulos** [comment]
We have just released 1.4 version - https://github.com/mediacms-io/mediacms/releases/tag/v1.4 - and the React code is included on frontend/ 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 

More development instructions will be added soon.
