### ISSUE TITLE
How does one set the theme default for everyone

### ISSUE THREAD

**Issue by timothevs** [mediacms-io/mediacms#70]
I can switch the theme to Dark when I am registered, and signed in. But I would like to switch the theme to dark for everyone by default, i.e. guests/non logged in users, etc. I looked in the `settings.py` and there is this

```python
DEFAULT_THEME = "black"  # this is not taken under consideration currently
```

Any idea if this can be done currently, or how long before this is implemented?

Thanks!

**Comment by mgogoulos** [comment]
Hi, edit file `templates/config/installation/site.html` and change mode in the first few lines to "dark" . Then restart mediacms 

`root@server /home/mediacms.io/mediacms # systemctl restart mediacms`

 and it will take effect (unless you're using the Docker installation, in this case I'm not sure whether the containers need restart or not after making the change to the file!)

Cheers

**Comment by timothevs** [comment]
Beautiful! Thank you for a great system. I was able to do this successfully.

**Comment by timfam** [comment]
Please note members can still changed theme as an option in the profile submenu.
