### ISSUE TITLE
500 error while "edit media"

### ISSUE THREAD

**Issue by dvaramoney** [mediacms-io/mediacms#717]
**Describe the issue**
I have newly installed the mediacms on ubuntu 20.04 VM. Installation was successful and I was able to login as admin and create user accounts etc.

The issue is while uploading the video, post successful uploading I am getting 500 error when I click on "edit media" and "edit subtitle"

**To Reproduce**
Steps to reproduce the issue:
1. Go to ... upload video -> edit media -> 500 error
2. Perform action ...
3. See error 500 on browser and GEThttps://URL/edit?m=wXdygkoi8
[HTTP/3 500 Internal Server Error 90ms]

**Environment (please complete the following information):**
 - OS:  ubuntu 20.04
 - Installation method: Single Server Installation
 - Browser, Firefox and chrome

**Comment by dvaramoney** [comment]
Updated DEBUG flag to True and getting the following details,

<html><body>
<h1>AttributeError
       at /edit</h1>
  <pre class="exception_value">'Settings' object has no attribute 'CRISPY_TEMPLATE_PACK'</pre>
  

Request Method: | GET
-- | --
https://URL/edit?m=wXdygkoi8
3.1.12
AttributeError
'Settings' object has no attribute 'CRISPY_TEMPLATE_PACK'
/home/mediacms.io/lib/python3.8/site-packages/django/conf/__init__.py, line 83, in __getattr__
/home/mediacms.io/bin/uwsgi
3.8.10
['/home/mediacms.io/mediacms',  '.',  '',  '/usr/lib/python38.zip',  '/usr/lib/python3.8',  '/usr/lib/python3.8/lib-dynload',  '/home/mediacms.io/lib/python3.8/site-packages']
Fri, 17 Feb 2023 09:35:03 +0000


</body>
</html>

**Comment by mgogoulos** [comment]
Thanks for opening this!

Looks like a bug with library versions not being pinned - this is a terrible practice but unfortunately is still in place. Looks like there's a new update on django-crispy-forms that did this, and the fact that this is not pinned means it will get the latest version. 

I'm going to create a quick fix for this

**Comment by mgogoulos** [comment]
PR ready and merged. Can you retry the installation? If it's a new environment, just do what you did for this installation. If you want to use the same environment, get the latest changes `git pull`, get the updates on python packages `pip install -r requirements.txt -U` and restart services `systemctl restart mediacms celery_short celery_long celery_beat`
