### ISSUE TITLE
Document how to set up a local development environment

### ISSUE THREAD

**Issue by betotorres** [mediacms-io/mediacms#726]
I've uploaded system code to VsCode and would like to implement some changes before putting a version into production. Is there any step by step to assemble this environment and guidelines on how to assemble a production version? I tried to run docker-compose-dev, but it doesn't even work, it gives an error.

**Comment by mgogoulos** [comment]
Hi, some instructions to start can be found on https://github.com/mediacms-io/mediacms/blob/main/docs/developers_docs.md#5-working-with-docker-tips, it would be great if you can help shape the documentation for local development. 

What is the error you are getting from compose-dev?

**Comment by mgogoulos** [comment]
I've just merged this PR https://github.com/mediacms-io/mediacms/pull/911 and will push a new latest release. 
Please check out the new page for local development and let me know how you find it (https://github.com/mediacms-io/mediacms/blob/main/docs/dev_exp.md)
