### ISSUE TITLE
Ubuntu 22.04?

### ISSUE THREAD

**Issue by ruvilonix** [mediacms-io/mediacms#748]
I see the recommendation to use Ubuntu 18 or 20. Is it not recommended to use 22.04, or has the documentation just not been updated yet?

**Comment by ruvilonix** [comment]
Ok, nevermind, I tried and it said the automatic script wouldn't work with any other versions.

**Comment by ruvilonix** [comment]
Sorry if this isn't the place, but I just have to say, it is amazing how easy this was to install. Compared to Peertube where I kept running into problem after problem, all I had to do here was let a script run, and the site is up and running after a few minutes. Thanks for making it simple!

**Comment by mgogoulos** [comment]
Thank you for your good words @ruvilonix ! I like to maintain the single server setup script because I think there are cases where it is still a better (or the only way to install) versus the Docker setup.
