### ISSUE TITLE
Reinstalling?

### ISSUE THREAD

**Issue by ruvilonix** [mediacms-io/mediacms#755]
What is the correct way to reinstall MediaCMS? I was messing around with my server and must have changed something which is causing a Server Error on MediaCMS. I don't have any content on it yet, so I don't mind reinstalling.

Or maybe someone knows where this error comes from:

```
django.db.utils.OperationalError: could not connect to server: Connection refused
	Is the server running on host "127.0.0.1" and accepting
	TCP/IP connections on port 5432?
```

I think all I was doing was removing/reinstalling openssl and openssh, so I'm guessing that's part of the cause.

Edit: I probably uninstalled some dependency. I decided to try just deleting the mediacms.io folder and running the install script again.

Edit2: No, that didn't work. Now instead of a Server Error on the login page, it's on every page. And there's nothing in debug.log anymore.

**Comment by ruvilonix** [comment]
I ended up just restoring my server from a backup. But it would be nice to know how to reinstall MediaCMS if needed.

**Comment by abdullahqureshi1994** [comment]
@mgogoulos It will be highly appreciated if you can let us know about how to reinstall the dockerized container along with previous data.

**Comment by mgogoulos** [comment]
There is an update section in https://github.com/mediacms-io/mediacms/blob/main/docs/admins_docs.md in both ways (single server / docker install) that should help until something more detailed is writen
