### ISSUE TITLE
Problems running in Portainer

### ISSUE THREAD

**Issue by behzad1993** [mediacms-io/mediacms#759]
**Describe the issue**
When i try to deploy it in portainer as a stack or in truenas as a docker-compose app, i'll receive always this error message. Using the docker compose script directly is working for me. 

**To Reproduce**
Steps to reproduce the issue:
1. Use Portainer Stack
2. Enter the yaml file to deploy

**Environment (please complete the following information):**
 - OS: MacOs & Debian
 - Installation method: Docker install

**Additional context**
there is already an issue opened since a few month, but i thought maybe it just got overlooked. If not close this.
https://github.com/mediacms-io/mediacms/issues/675

**Comment by OpenElectronika** [comment]
I keep having the same issue without the use of Portainer. I was able to get v1.7 working with Docker-Desktop, which can be downloaded here:
https://github.com/mediacms-io/mediacms/releases/tag/v1.7

Extract it do your intended directory and navigate to it using the cd command.
Then create a new container using docker-compose file: docker-compose up -d

**Comment by srvprivate** [comment]
> I keep having the same issue without the use of Portainer. I was able to get v1.7 working with Docker-Desktop, which can be downloaded here: https://github.com/mediacms-io/mediacms/releases/tag/v1.7
> 
> Extract it do your intended directory and navigate to it using the cd command. Then create a new container using docker-compose file: docker-compose up -d

This works. Run a git clone or docker pull ito the directory your yaml is in. Make sure in compose you have the docker deploy mapped to wherever its source code is. THEN docker compose UP. Just make sure you clone so you get ALL the data. It's looking for that docker deploy folder with install.sh. Got it working on Docker for Unraid

**Comment by mgogoulos** [comment]
Not sure what is the issue here since I don't have access to such an environment. Closing as there are no resources to work on it, plus it looks as @srvprivate has a workaround
