### ISSUE TITLE
Summary of improvement suggestions for some functions of Mediacms

### ISSUE THREAD

**Issue by cdorsat** [mediacms-io/mediacms#768]
Suggestions for improving some functions of Mediacms

I like this system very much, thanks to the hard work of the developers. The current test found the following problems:

File Upload:
1. The file cannot be uploaded when the file name is too long or has special characters (this is a BUG).

2. When multiple files (the average size of a single file is 1.4G) are uploaded and transcoded at the same time, the upload of the second or third file fails (this is a BUG).
**The situation when an error occurs is as follows:**
![Capture1](https://github.com/mediacms-io/mediacms/assets/22068633/cd05859d-28d8-4f21-ab57-5516d09b18c0)

User experience (function improvement):

1. Add the logo corresponding to the user on the player homepage and the left side of the media file.

![Youtube compare](https://user-images.githubusercontent.com/22068633/232226738-93fe5e22-1a44-4d1f-aacc-050afcb1d2dd.png)

![User Icon](https://user-images.githubusercontent.com/22068633/232226775-400e4d95-1b7e-4b05-a7ac-dfe06577714e.png)

4. The mouse pointer cannot be automatically hidden when it is not in full screen state.

5. In the **About section** of the **user profile page**, the text processing is not beautiful enough, such as support for text wrapping, color Logo, and text editing.

6. The player adds the **HD logo**.
**Mediacms current:**
![Untitled](https://github.com/mediacms-io/mediacms/assets/22068633/5b6bc8a5-23c4-4699-be51-c53d6d0b9986)

**About HD Icon:**
![HD Icon 2](https://user-images.githubusercontent.com/22068633/232373185-58205492-bc25-4009-a407-a46057e1792b.png)
![HD Icon](https://user-images.githubusercontent.com/22068633/232373188-caae6657-838e-4735-b258-55135d9fe159.png)

7. The player cannot play webm format and **2160p HD** files.

8. Add multi-language function, and the translation work can be done by the user.
 
9. **Tags** do not support text other than English, such as Chinese.

10. **Username** does not support the symbol "-", for example: "user-abcd123".

11. Suggestion for improvement: When a media file containing a playlist is found, the playlist should be displayed in the search content. for example:
![Untitled](https://github.com/mediacms-io/mediacms/assets/22068633/ebce9378-e9de-409d-aa76-b7c5472c96b3)

12. These two buttons. User information and classifications of the entire website may be leaked here, and it is recommended to improve it to ensure the security of the website.
![Untitled](https://github.com/mediacms-io/mediacms/assets/22068633/3b34085e-8318-49c3-87ff-67a27080df21)

**Comment by mgogoulos** [comment]
Thank you for your good words and for taking the time to make these suggestions. 

In general I see two categories here, a) bugs, b) feature requests. Ideally each of the bugs should be opened as an issue here, and each of the feature requests as a  request on the Discussion section. 

It is very hard to track a specific item out of these now and possibly work on it, versus having each of the items filled as an issue (for bugs) and feature requests on Discussions for the requests. Thus each issue or request can have their own tags/priority and text. Also some of the issues would be closed, if they are already opened as duplicates.

**Comment by cdorsat** [comment]
I am really sorry, the reason is that I am not familiar with the operation and use of Github, I will pay attention next time.

The above are the problems I found. For the details of each problem, you can use YouTube as a reference and comparison.

Thanks again for your contribution!

**Comment by mgogoulos** [comment]
Thanks again for the aim to contribute and the effort!

**Comment by mgogoulos** [comment]
I see you've opened all of the items as separate ones (and as you've seen I've moved some of them to discussions/feature requests, to reserve the Issues section for problems/bugs mostly) so this can be closed. Thanks!
