### ISSUE TITLE
Prevent video leeching / Hotlinking

### ISSUE THREAD

**Issue by xioahei20** [mediacms-io/mediacms#77]
Prevent bandwidth theft. The URL of the M3U8 file is dynamically encrypted based on the password and timestamp, and is changed every few minutes.

**Comment by mgogoulos** [comment]
Hi, can you describe the use case you have in mind?

**Comment by xioahei20** [comment]
https://www.leimulamu.com/play/5c5eb2c76cd6b06cc92b77f8

**Comment by swiftugandan** [comment]
hotlinking - https://www.namecheap.com/support/knowledgebase/article.aspx/9997/2194/what-is-hotlinking-and-how-to-prevent-it/

Seen this on the shared file above, the random seed keeps changing
<img width="772" alt="Screenshot 2021-03-12 at 21 29 42" src="https://user-images.githubusercontent.com/724629/111000687-69d8d980-837a-11eb-8776-3a891da09d0d.png">

**Comment by mgogoulos** [comment]
this is not something we're planning to work - at least anytime soon
