### ISSUE TITLE
Question about video transcoding.

### ISSUE THREAD

**Issue by cdorsat** [mediacms-io/mediacms#771]
Uploaded videos are transcoded at sizes other than the system defaults, and these sizes are uncommon. The system transcoding setting size is only **240**, **360**, **480**, **720** and **1080**.

![Untitled1](https://github.com/mediacms-io/mediacms/assets/22068633/c2ad6387-eecf-4eec-9d1f-92075e0e3240)

![Untitled6](https://github.com/mediacms-io/mediacms/assets/22068633/c464f87f-1b2c-4f88-94dc-9b0eecb05450)

**Comment by morbificagent** [comment]
Have this on my site too, but only with some of the uploaded videos.
Most of them are transcoded to common resolutions.
Try to find out whats the difference between these files...

**Comment by mgogoulos** [comment]
It's the same issue as https://github.com/mediacms-io/mediacms/issues/824 , will handle soon
