### ISSUE TITLE
Videos no longer play after update

### ISSUE THREAD

**Issue by nbl0** [mediacms-io/mediacms#773]
**Describe the issue**
After a simple update by following the step in the documentation like this: 

cd /home/mediacms.io/mediacms # enter mediacms directory
source  /home/mediacms.io/bin/activate # use virtualenv
git pull # update code
python manage.py migrate # run Django migrations
sudo systemctl restart mediacms celery_long celery_short # restart services

I'm incapable to play any videos on my website. The page loads, and I have a black screen instead of the video without the play, sound button, ...

**Screenshots**
[example](https://image.noelshack.com/fichiers/2023/20/7/1684694094-screenshot-20230521-203252.png)

**Environment (please complete the following information):**
 - OS: debian 11.7
 - Installation method: single server install
 - Browser: firefox, chrome

**Comment by mgogoulos** [comment]
Can you do a shift+refresh on the browser? Could be something related with caching. 
If this does not help, can you open the Console of the browser and see what logs this brings (and paste it here)?

**Comment by nbl0** [comment]
Hello,

> Can you do a shift+refresh on the browser? Could be something related with caching.

It does not change anything.

> If this does not help, can you open the Console of the browser and see what logs this brings (and paste it here)?

Yes, sir:

VIDEOJS: WARN: videojs.plugin() is deprecated; use videojs.registerPlugin() instead video.min.js:2:1659
VIDEO DEBUG: Video files don't exist media.js:1:16533
Source map error: Error: NetworkError when attempting to fetch resource.
Resource URL: moz-extension://bf1ab15b-202c-4151-bf9c-e41ccb7eaae2/ad-blocker/content.js
Source Map URL: panelos-content.js.map
Source map error: Error: NetworkError when attempting to fetch resource.
Resource URL: moz-extension://20e04cf5-2c66-4461-a64e-2918f7187d43/model/static/DOMPurify/purify.min.js
Source Map URL: purify.min.js.map
Error: Promised response from onMessage listener went out of scope build.js:2:93325

Thank you very much for your help.

**Comment by mgogoulos** [comment]
Mmm hard to tell from this ;( Does `git pull` finish without errors? Do you see anything else on Console of the browse, like files that are not downloaded? (eg 40x errors)...

**Comment by mgogoulos** [comment]
mmm could it be something related with permissions? for example having installed while being  logged in as root, and then you are updating as a user?

**Comment by nbl0** [comment]
Yes, you right. I think the problem appeared because of this.
Nonetheless, I change recursively the owner's repository, now it's www-data, with the chown command but that not help much.

Thank you for your help and sorry I'm new to server admin.

**Comment by nbl0** [comment]
I still haven't found a solution to my problem.
Nevertheless, in the administration part of the site, the videos are accessible via the following url, for example:

**mysite.com/media/original/user/admin/8a09dabf525445a4a188d7950bc38d44.bla_bla_bla.mp4**

What should I conclude from this? The link that points to the videos in the frontend part is broken? Where can I check this?

**Comment by mgogoulos** [comment]
If this is a public portal and not inside a VPN or something like that, I can have a quick look and see what could be the issue, since if it is an issue with the upgrade it would benefit to know.
