### ISSUE TITLE
support language switching?

### ISSUE THREAD

**Issue by RosaiK** [mediacms-io/mediacms#837]
Hello!

Thank you very much for developing such an excellent cms.
I want to make a video website about Buddhist knowledge.
Does it support language switching? How to do it?

Thanks!
Best Regards.

**Comment by mgogoulos** [comment]
Hi @RosaiK , Language Switching isn't something supported yet

**Comment by RosaiK** [comment]
May I ask where the text of the sliderbar on the left can be modified,
thank you

Markos Gogoulos ***@***.***> 于2023年7月10日周一 02:35写道：
