### ISSUE TITLE
Update from 2 to 3: Module 'cms' has no attribute 'celery'

### ISSUE THREAD

**Issue by foMXdsyZHPY0** [mediacms-io/mediacms#841]
**Describe the issue**
Followed update procedures for server installation (https://github.com/mediacms-io/mediacms/blob/main/docs/admins_docs.md#2-server-installation).
`systemctl restart celery_long.service celery_short.service` fails with

```
Job for celery_long.service failed because the control process exited with error code.
See "systemctl status celery_long.service" and "journalctl -xeu celery_long.service" for details.
Job for celery_short.service failed because the control process exited with error code.
See "systemctl status celery_short.service" and "journalctl -xeu celery_short.service" for details.
```

`journalctl -xeu celery_long.service` shows:

```
Jul 17 14:32:09 vtube-dev sh[2419]: Usage: celery [OPTIONS] COMMAND [ARGS]...
Jul 17 14:32:09 vtube-dev sh[2419]: Try 'celery --help' for help.
Jul 17 14:32:09 vtube-dev sh[2419]: Error: Invalid value for '-A' / '--app':
Jul 17 14:32:09 vtube-dev sh[2419]: Unable to load celery application.
Jul 17 14:32:09 vtube-dev sh[2419]: Module 'cms' has no attribute 'celery'
Jul 17 14:32:09 vtube-dev systemd[1]: celery_long.service: Control process exited, code=exited, status=2/INVALIDARGUMENT
```

**To Reproduce**
Steps to reproduce the issue:
1. Followed update procedures for server installation (https://github.com/mediacms-io/mediacms/blob/main/docs/admins_docs.md#2-server-installation).

**Expected behavior**
Services should start.

**Screenshots**
None

**Environment (please complete the following information):**
 - OS: Debian 11 and 12
 - Installation method: Single server install
 - Python 3.11.2

**Additional context**

**Comment by mgogoulos** [comment]
I see, the celery files for systemd have to be copied as well. I've updated the docs, checkout the link you provided and see the new notes. Try it out and let me know if it worked for you, so I can close this ticket

**Comment by foMXdsyZHPY0** [comment]
Thanks for doc update, it worked!

**Comment by mgogoulos** [comment]
Thanks for confirming! Don't forget to add an entry on https://github.com/mediacms-io/mediacms/discussions/categories/show-and-tell if you want to share what you're building!
