### ISSUE TITLE
Configuration.md not clear on role of docker/local_settings.py

### ISSUE THREAD

**Issue by Dan1ell** [mediacms-io/mediacms#85]
(Making an issue from discussion to link to PR)

In [the docs](https://github.com/mediacms-io/mediacms/blob/main/docs/Configuration.md) it says:

> A number of options are available on cms/settings.py.
> It is advisable to override any of them by adding it to cms/local_settings.py .
> Any change needs restart of MediaCMS in order to take effect. So edit cms/local_settings.py, make a change and restart MediaCMS

But when I change something in cms/local_settings.py and restart MediaCMS, this seems to reset cms/local_settings.py to its original content. After a while I realized the file was being overwritten with whatever is written in deploy/docker/local_settings.py.
I installed MediaCMS with the Docker Compose installation so I guess that makes sense.

But the text in Configuration.md isn't clear on this point and could be made clearer. The deploy/docker/local_settings.py file is only mentioned in the installation instructions on the main page. It could be mentioned here in Configuration.md as well.

_Originally posted by @Dan1ell in https://github.com/mediacms-io/mediacms/discussions/76_

**Comment by swiftugandan** [comment]
https://github.com/mediacms-io/mediacms/pull/86 should fix this

**Comment by swiftugandan** [comment]
@mgogoulos I think this is now fixed

**Comment by mgogoulos** [comment]
more documentation to be added soon, closing
