### ISSUE TITLE
db_1 FATAL:  role "root" does not exist

### ISSUE THREAD

**Issue by urza** [mediacms-io/mediacms#894]
I installed mediacms via docker compose on ubuntu server 22.04.
I see a lot of these in output:

`db_1             | 2023-10-04 18:53:50.517 BST [61499] FATAL:  role "root" does not exist`

Is this something I need to fix somehow or is it ok to ignore?

**Comment by mgogoulos** [comment]
This is a message that can be ignored, but since it's spamming logs should be removed (fix has to be trivial)

**Comment by vijaykumar1710** [comment]
@mgogoulos is there way we can get rid of this and use the app locally on macbook? serving locally also from docker only.

**Comment by joon612** [comment]
Same issue here, is there any update?

**Comment by makerduck** [comment]
As mentioned in #1002 there's a fix from @Nouri-redouane to suppress the output:
in the docker-compose.yaml got to "db: healthcheck:" and edit `"pg_isready"` to 

`"pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"`

worked fine for me

**Comment by working-name** [comment]
@makerduck that might work with the defaults but not if you actually bothered to change the env vars. Now getting unknown role for whatever I called the POSTGRES_USER which is `poopoo`:

```
mediacms-db-1             | 2024-06-10 04:08:03.095 BST [107] FATAL:  role "poopoo" does not exist
```

So I think this points to an issue in the setup process as well.

**Comment by mgogoulos** [comment]
Pr was merged and this is fixed now!
