### ISSUE TITLE
Allow streaming of original media files

### ISSUE THREAD

**Issue by a20eac1d** [mediacms-io/mediacms#907]
**Describe the feature you'd like**
I would like to be able to stream the originally uploaded media files without re-encoding them first.

**Additional context**
I am running MediaCMS on a Raspberry Pi. This device is EXTREMELY slow at video encoding, even H264 at 240p takes forever.

I am already uploading the video files in a format and resolution that can be played and streamed (H264, 1080p, 30 fps).

Unfortunately, MediaCMS forces me to use at least one re-encoding format for the videos to be playable, instead of simply using the media file that is already working perfectly.

MediaCMS would be perfect for my use case. Unfortunately, this issue is making it impossible to use on devices like the Raspberry Pi. I literally cannot upload and process a single video while this issue exists, therefore I have to stop using it until this issue is fixed.

I would really appreciate your input and maybe a fix for this issue, if you have the time! Thank you so much!

**Comment by a20eac1d** [comment]
Amazing, thank you for your response! Unfortunately, that branch is quite far behind main if I understand it correctly, so I don't feel comfortable running my instance on this version. Do you have any rough estimate when the merge will happen? Can I do something to help you with this?

**Comment by mgogoulos** [comment]
PR is now merged, checkout the note on https://github.com/mediacms-io/mediacms/blob/main/docs/admins_docs.md
