### ISSUE TITLE
Missing encodings_info after 2.x to 3.x upgrade 

### ISSUE THREAD

**Issue by clnsdev** [mediacms-io/mediacms#921]
**Description**
After following the upgrade suggestions I get the following error thrown by _common.js: _TypeError: t.props.data.encodings_info is undefined_ when opening a video url, resulting in a blank page.
It appears that the _encodings_info_ object is missing in the json returned by the api interface, I tried using the _Generate missing encoding(s)_ option recently added to the medias section, but without success. 

**Screenshots**
![image](https://github.com/mediacms-io/mediacms/assets/19185101/3ff5e0fd-31c6-4764-939f-21f61fbeb58f)

**Environment**
 - OS: Debian 12 bookworm
 - Installation method: single server install

**Comment by Galactix** [comment]
I am trying MediaCMS for the first time today. And I also got the error with encoding video.

`VIDEOJS: WARN: videojs.plugin() is deprecated; use videojs.registerPlugin() instead`

**Comment by clnsdev** [comment]
> I am trying MediaCMS for the first time today. And I also got the error with encoding video.
> 
> `VIDEOJS: WARN: videojs.plugin() is deprecated; use videojs.registerPlugin() instead`

Hi! That is just a deprecation warning coming from the videojs plugin and shouldn't be of concern until its developers decide to dismiss it in a future release. In your case the page works correctly showing the video anyway, right?
Unfortunately, in the case I'm reporting, the missing _encodings_info_ blocks the page rendering process, resulting in a blank page.

**Comment by mgogoulos** [comment]
Hi @clnsdev , I can only assume that something didn't go well with the `git pull` (assuming you did that). Is there any conflicts locally? Does 'python manage.py migrate' end up correctly?

**Comment by clnsdev** [comment]
@mgogoulos I really can't remember seeing particular error messages at the time, but reverting and reapplying the pull + migration did the magic. 
Thank you very much,  I'll post the bash shell steps that helped me solving the problem. 

```shell
$ sudo systemctl stop mediacms celery_long celery_short celery_beat
cd your-mediacms-git-base-path
$ git reflog show
c5047d8 (HEAD -> main, origin/main, origin/HEAD) HEAD@{0}: pull: Fast-forward
cd8d0ea HEAD@{1}: clone: from https://github.com/mediacms-io/mediacms
$ git reset --hard cd8d0ea
$ git pull
$ . ../bin/activate
($) python manage.py makemigrations
Migrations for 'files':
  files/migrations/0005_alter_media_is_reviewed.py
    - Alter field is_reviewed on media
($) python manage.py migrate
Operations to perform:
  Apply all migrations: account, actions, admin, auth, authtoken, contenttypes, files, sessions, sites, socialaccount, users
Running migrations:
  Applying files.0005_alter_media_is_reviewed... OK
($) deactivate
$ sudo systemctl start mediacms celery_long celery_short celery_beat
``` 
For clarity I omitted some longer outputs (like in the git reset command). 
It seems the that specific migration file went mysteriously missing last time, I would speculate it was probably due some subfolder write permission problem. 
The _($)_ means a python environment context. 
And that's it, ready to close, thanks again! 😉
