### ISSUE TITLE
Player wont show all encoding formats

### ISSUE THREAD

**Issue by jmoschetti45** [mediacms-io/mediacms#957]
I've setup a few other formats (and removed a few) from the default encoders. The ones I've removed from the encoding list disappear from the player quality options, but the ones I've added don't appear.

The transcoded files exist and play fine manually, and show up in the download list.

All h264 like the defaults, just different resolutions. 1440 and 2160 since I have a lot of 4k and 8k content.

Current git pull from 1/13/2024, everything else works.

**Comment by mgogoulos** [comment]
This is now fixed in v4.2.0, there was indeed an error that is now fixed
