### ISSUE TITLE
Relative urls needed for menu items

### ISSUE THREAD

**Issue by Dan1ell** [mediacms-io/mediacms#96]
Most menu items don’t have relative urls and break when not running on a local machine.  

When running MediaCMS from a server and accessing it with the server’s ip address, the menu items try to resolve to ‘localhost/item’ and of course there is nothing running on localhost, which is my laptop.

URLs that break:
Home: localhost 
Featured: localhost/featured 
Recommended: localhost/recommended
Recent uploads: localhost/latest
Tags: localhost/tags
Categories: localhost/categories
Members: localhost/members
History: localhost/history
Liked media: localhost/liked
Sign in: localhost/accounts/login
Register:  localhost/accounts/signup
MediaCMS logo: localhost

URLs that work:
/about
/terms
/contact

De logo images are also not loading properly on the server.

**Comment by mgogoulos** [comment]
There's a dependency on the `FRONTEND_HOST` variable that results in this, when you are using the ip address directly. Probably it should be removed, but this need some frontend work too.

**Comment by mgogoulos** [comment]
This is related with https://github.com/mediacms-io/mediacms/issues/101

**Comment by Dan1ell** [comment]
After changing FRONTEND_HOST to the server's ip address in deploy/docker/local_settings.py, restarting the server, and then running docker-compose up, MediaCMS navigates correctly now. Still worth fixing though.

**Comment by mgogoulos** [comment]
this is handled with https://github.com/mediacms-io/mediacms/issues/101
