### ISSUE TITLE
SMTP not working

### ISSUE THREAD

**Issue by SKJoy** [mediacms-io/mediacms#984]
**Describe the issue**
SMTP settings been set as per instruction but contact form notification is not being sent to admin emails.

**To Reproduce**
Steps to reproduce the issue:
1. Set SMTP settings in settings.py (as well in local_settings.py)
2. Restart MediCMS server
3. Go to MediaCMS Contact form and submit a message
4. Notification never received to the admin emails

**Expected behavior**
Contact form message notification should arrive at admin emails.

**Environment (please complete the following information):**
 - OS: Ubuntu Linux
 - Installation method: Single server install

**Additional context**
## SMTP settings
EMAIL_HOST = "mail.smtp_server.com"
EMAIL_HOST_USER = "mediacms.test@smtp_server.com"
EMAIL_HOST_PASSWORD = "CORRECT_PASSWORD"
EMAIL_PORT = 587
EMAIL_USE_TLS = True
DEFAULT_FROM_EMAIL = "mediacms.test@smtp_server.com"
SERVER_EMAIL = DEFAULT_FROM_EMAIL
ADMIN_EMAIL_LIST = ["admin_1@domain.com", "admin_2@domain.com"]

**Test information**
- SMTP settings were tested with WebMail & Mail clients and been found 100% working.
- Tested with manage.py SHELL and the test succeeded, we received test emails

**Comment by SKJoy** [comment]
The SMTP configuration seemed to work after a server REBOOT! Is there a simpler way to reflect the configuration without a server reboot?

**Comment by gamebird92** [comment]
I also did recognize that the SMTP configuration needs a server reboot... 
(Running single server install on Ubuntu 22.04)
